# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'auto_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_autoMainForm(object):
    def setupUi(self, autoMainForm):
        autoMainForm.setObjectName("autoMainForm")
        autoMainForm.resize(480, 140)
        self.inputLabel = QtWidgets.QLabel(autoMainForm)
        self.inputLabel.setGeometry(QtCore.QRect(20, 10, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.inputLabel.setFont(font)
        self.inputLabel.setObjectName("inputLabel")
        self.charTxtEdit = QtWidgets.QTextEdit(autoMainForm)
        self.charTxtEdit.setGeometry(QtCore.QRect(170, 24, 181, 25))
        self.charTxtEdit.setObjectName("charTxtEdit")
        self.okBtn = QtWidgets.QPushButton(autoMainForm)
        self.okBtn.setGeometry(QtCore.QRect(370, 20, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.okBtn.setFont(font)
        self.okBtn.setObjectName("okBtn")
        self.okTxtLabel = QtWidgets.QLabel(autoMainForm)
        self.okTxtLabel.setGeometry(QtCore.QRect(30, 70, 421, 41))
        self.okTxtLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.okTxtLabel.setObjectName("okTxtLabel")

        self.retranslateUi(autoMainForm)
        QtCore.QMetaObject.connectSlotsByName(autoMainForm)

    def retranslateUi(self, autoMainForm):
        _translate = QtCore.QCoreApplication.translate
        autoMainForm.setWindowTitle(_translate("autoMainForm", "Form"))
        self.inputLabel.setText(_translate("autoMainForm", "문자를 입력하세요 : "))
        self.okBtn.setText(_translate("autoMainForm", "확인"))
        self.okTxtLabel.setText(_translate("autoMainForm", "확인을 누르면 여기에 입력한 글이 출력됩니다."))
